// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHh0uD0AVRsdJKzX0YFqv5aO9w85FhLk',
    appId: '1:859067251975:web:35a1a8489083bff7f899a2',
    messagingSenderId: '859067251975',
    projectId: 'fluttercrudkevin',
    authDomain: 'fluttercrudkevin.firebaseapp.com',
    databaseURL: 'https://fluttercrudkevin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttercrudkevin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvWxvcrzeYVR-RtR4qG8Zl3GCpSXwnGqU',
    appId: '1:859067251975:android:9559690b391217b9f899a2',
    messagingSenderId: '859067251975',
    projectId: 'fluttercrudkevin',
    databaseURL: 'https://fluttercrudkevin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttercrudkevin.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxHh0uD0AVRsdJKzX0YFqv5aO9w85FhLk',
    appId: '1:859067251975:web:d225b2fbdc4f8deaf899a2',
    messagingSenderId: '859067251975',
    projectId: 'fluttercrudkevin',
    authDomain: 'fluttercrudkevin.firebaseapp.com',
    databaseURL: 'https://fluttercrudkevin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttercrudkevin.appspot.com',
  );

}